# Generated by Django 3.1.5 on 2021-01-17 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nombre del reporte')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nombre de la vista en la base de datos', max_length=50, unique=True, verbose_name='Vista a consultar')),
                ('sheet_name', models.CharField(help_text='Nombre de la hoja creada', max_length=50, verbose_name='Nombre de la hoja')),
                ('main_period', models.CharField(blank=True, default=None, help_text='Columna de periodo en la vista para filtrar', max_length=50, verbose_name='Columna de periodo')),
                ('main_program', models.CharField(blank=True, default=None, help_text='Columna de programa en la vista para filtrar', max_length=50, verbose_name='Columna de programa')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportViewRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapapp_ms.report')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='uapapp_ms.view')),
            ],
        ),
    ]
