# Generated by Django 3.1.5 on 2021-01-31 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapapp_ms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='text_period',
            field=models.CharField(blank=True, default=None, help_text='Columna con los nombres de periodo para mostrar', max_length=50, verbose_name='Columna de nombre periodo'),
        ),
        migrations.AddField(
            model_name='view',
            name='text_program',
            field=models.CharField(blank=True, default=None, help_text='Columna con los nombres de programa para mostrar', max_length=50, verbose_name='Columna de nombre programa'),
        ),
        migrations.AlterField(
            model_name='view',
            name='main_period',
            field=models.CharField(blank=True, default=None, help_text='Columna con los códigos de periodo en la vista para filtrar', max_length=50, verbose_name='Columna de código periodo'),
        ),
        migrations.AlterField(
            model_name='view',
            name='main_program',
            field=models.CharField(blank=True, default=None, help_text='Columna con los códigos de programa en la vista para filtrar', max_length=50, verbose_name='Columna de código programa'),
        ),
    ]
