# Generated by Django 3.1.5 on 2021-01-15 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uapapp_ms', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Views',
            new_name='View',
        ),
    ]
