# Generated by Django 3.1.5 on 2021-01-15 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapapp_ms', '0002_auto_20210115_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Nombre del reporte'),
        ),
        migrations.AlterField(
            model_name='view',
            name='view',
            field=models.CharField(max_length=50, verbose_name='Vistas a consultar'),
        ),
    ]
