# Generated by Django 3.1.5 on 2021-01-31 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapapp_ms', '0002_auto_20210131_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='description',
            field=models.TextField(default='', verbose_name='Descripción'),
        ),
    ]
