# Generated by Django 3.1.5 on 2021-02-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapapp_ms', '0003_report_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='report',
            name='category',
            field=models.TextField(choices=[('RE', 'Reporte'), ('FR', 'Formato De Recoleccion')], default='RE', verbose_name='Categoria'),
        ),
        migrations.AddField(
            model_name='report',
            name='subformat',
            field=models.CharField(default='', help_text='Solo aplica en el caso de los formatos de recolección', max_length=50, verbose_name='Sub-formato'),
        ),
    ]
