# Generated by Django 3.1.5 on 2021-02-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapapp_ms', '0004_auto_20210202_0526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='subformat',
        ),
        migrations.AddField(
            model_name='report',
            name='_format',
            field=models.CharField(default='', help_text='Solo aplica en el caso de los formatos de recolección', max_length=50, verbose_name='Formato'),
        ),
        migrations.AddField(
            model_name='report',
            name='level',
            field=models.TextField(choices=[('PRE', 'Pregrado'), ('POS', 'Posgrado'), ('NA', 'No Aplica')], default='NA', help_text='Nivel de la información', verbose_name='Nivel'),
        ),
    ]
