# Generated by Django 3.1.5 on 2021-02-02 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapapp_ms', '0005_auto_20210202_0602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='_format',
            field=models.TextField(choices=[('Admitidos', 'Admitidos'), ('Docentes', 'Docentes'), ('Egresados', 'Egresados'), ('Estudiantes', 'Estudiantes'), ('Generales', 'Generales'), ('Investigacion', 'Investigacion'), ('Programa', 'Programa'), ('NA', 'No Aplica')], default='NA', help_text='Solo aplica en el caso de los formatos de recolección', verbose_name='Formato'),
        ),
    ]
