# Generated by Django 3.1.5 on 2021-02-07 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uapapp_ms', '0007_auto_20210207_0136'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='period',
            options={'ordering': ['-code']},
        ),
        migrations.AlterField(
            model_name='report',
            name='periods',
            field=models.ManyToManyField(blank=True, to='uapapp_ms.Period', verbose_name='Periodos'),
        ),
    ]
